version: '3.0'
services:
  test_db:
    container_name: 'test_db'
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=test_postgres
      - POSTGRES_PASSWORD=test_postgres
      - POSTGRES_DB=test_postgres
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_postgres']
      interval: 10s
      timeout: 5s
      retries: 5
