version: "3.0"
services:
  band_tracker_db:
    container_name: "band_tracker_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
  band_tracker_test_db:
    container_name: "band_tracker_test_db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TEST_DB_LOGIN}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - "5433:5432"
  band_tracker_rabbitmq:
    container_name: "band_tracker_rabbitmq"
    image: rabbitmq:3.12-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=band-tracker
      - RABBITMQ_DEFAULT_PASS=band-tracker
    ports:
      - 5672:5672
      - 15672:15672
