services:
  app:
    build: .
    volumes:
      - .:/app
      - ./band_tracker:/app/data
  band_tracker_db:
    container_name: "band_tracker_db"
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
volumes:
  pgdata:
    name: "pgdata"
