services:
  app:
    build: .
    volumes:
      - .:/app
      - ./band_tracker:/app/data
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5434:5432'
volumes:
  pgdata:
    name: "pgdata"