"""add artist socials table

Revision ID: 0adc14e989cf
Revises: 5650586174c2
Create Date: 2023-07-09 18:18:30.267448

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0adc14e989cf"
down_revision = "5650586174c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist_socials",
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("instagram", sa.String(), nullable=True),
        sa.Column("spotify", sa.String(), nullable=True),
        sa.Column("youtube", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("artist_id"),
    )
    op.drop_column("artist", "youtube_link")
    op.drop_column("artist", "inst_link")
    op.drop_column("artist", "spotify")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artist", sa.Column("spotify", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "artist",
        sa.Column("inst_link", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "artist",
        sa.Column("youtube_link", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("artist_socials")
    # ### end Alembic commands ###
