"""add is_notified fields

Revision ID: 12695e06cae8
Revises: 28306be64a71
Create Date: 2024-02-07 16:52:23.297787

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "12695e06cae8"
down_revision = "28306be64a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_artist", sa.Column("is_notified", sa.Boolean(), nullable=False)
    )
    op.drop_column("event_artist", "notified")
    op.add_column("event_user", sa.Column("is_notified", sa.Boolean(), nullable=False))
    op.create_index(
        op.f("ix_event_user_is_notified"), "event_user", ["is_notified"], unique=False
    )
    op.add_column(
        "notification", sa.Column("is_notified", sa.Boolean(), nullable=False)
    )
    op.create_index(
        op.f("ix_notification_is_notified"),
        "notification",
        ["is_notified"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_is_notified"), table_name="notification")
    op.drop_column("notification", "is_notified")
    op.drop_index(op.f("ix_event_user_is_notified"), table_name="event_user")
    op.drop_column("event_user", "is_notified")
    op.add_column(
        "event_artist",
        sa.Column("notified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("event_artist", "is_notified")
    # ### end Alembic commands ###
