"""make tg_id user field unique

Revision ID: 46b3ad61f509
Revises: 7b6d0f69c831
Create Date: 2023-11-02 10:57:03.691230

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "46b3ad61f509"
down_revision = "7b6d0f69c831"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_tg_id_unique", "user", ["tg_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_tg_id_unique", "user", type_="unique")
    # ### end Alembic commands ###
