"""remove upcoming events cnt

Revision ID: 5650586174c2
Revises: d655bbfe1422
Create Date: 2023-07-08 17:53:38.558929

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5650586174c2"
down_revision = "d655bbfe1422"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artist", "upcoming_events_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artist",
        sa.Column(
            "upcoming_events_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
