"""add artist aliases

Revision ID: 67a7a7e52fb3
Revises: 7b59e8b9925a
Create Date: 2023-08-10 17:41:49.640706

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "67a7a7e52fb3"
down_revision = "7b59e8b9925a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist_alias",
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("alias"),
    )
    op.create_unique_constraint("artist_tm_data_unique_id", "artist_tm_data", ["id"])
    op.create_unique_constraint("event_tm_data_unique_id", "event_tm_data", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("event_tm_data_unique_id", "event_tm_data", type_="unique")
    op.drop_constraint("artist_tm_data_unique_id", "artist_tm_data", type_="unique")
    op.drop_table("artist_alias")
    # ### end Alembic commands ###
