"""delete images and new fields

Revision ID: 7b59e8b9925a
Revises: 8c12ce7bcc0a
Create Date: 2023-07-11 18:28:42.477917

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b59e8b9925a"
down_revision = "8c12ce7bcc0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artist_image")
    op.drop_table("event_image")
    op.add_column("artist", sa.Column("image", sa.String(), nullable=True))
    op.add_column("event", sa.Column("image", sa.String(), nullable=True))
    op.add_column("sales", sa.Column("sale_start", sa.DateTime(), nullable=True))
    op.add_column("sales", sa.Column("sale_end", sa.DateTime(), nullable=True))
    op.alter_column("sales", "price_max", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("sales", "price_min", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("sales", "currency", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("sales", "on_sale")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sales", sa.Column("on_sale", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.alter_column("sales", "currency", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("sales", "price_min", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("sales", "price_max", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("sales", "sale_end")
    op.drop_column("sales", "sale_start")
    op.drop_column("event", "image")
    op.drop_column("artist", "image")
    op.create_table(
        "event_image",
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
            name="event_image_event_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "url", name="event_image_pkey"),
    )
    op.create_table(
        "artist_image",
        sa.Column("artist_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name="artist_image_artist_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("artist_id", "url", name="artist_image_pkey"),
    )
    # ### end Alembic commands ###
