"""add tg_id user field

Revision ID: 7b6d0f69c831
Revises: f9ea2453a9bf
Create Date: 2023-11-02 10:50:10.091303

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b6d0f69c831"
down_revision = "f9ea2453a9bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("tg_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "tg_id")
    # ### end Alembic commands ###
