"""add notified field to EventArtist

Revision ID: 82cd26ecbdef
Revises: 8584d65027c3
Create Date: 2023-08-11 21:14:06.241072

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82cd26ecbdef"
down_revision = "8584d65027c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_artist",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
    )
    op.add_column("event_artist", sa.Column("notified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_artist", "notified")
    op.drop_column("event_artist", "id")
    # ### end Alembic commands ###
