"""fix nullable constraints

Revision ID: 8584d65027c3
Revises: 67a7a7e52fb3
Create Date: 2023-08-11 14:54:06.071942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8584d65027c3"
down_revision = "67a7a7e52fb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("artist", "tickets_link", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("event", "venue", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("event", "venue_city", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "event", "venue_country", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("event", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("event", "ticket_url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("event", "ticket_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("event", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("event", "venue_country", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("event", "venue_city", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("event", "venue", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "artist", "tickets_link", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
