"""remove unique user_id field in message

Revision ID: 86eefd16e336
Revises: cb4fb4355c24
Create Date: 2023-12-13 17:31:21.317378

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86eefd16e336"
down_revision = "cb4fb4355c24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription")
    op.drop_index("ix_message_user_id", table_name="message")
    op.create_index(op.f("ix_message_user_id"), "message", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_user_id"), table_name="message")
    op.create_index("ix_message_user_id", "message", ["user_id"], unique=False)
    op.create_table(
        "subscription",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("artist_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name="subscription_artist_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="subscription_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "artist_id", name="subscription_pkey"),
    )
    # ### end Alembic commands ###
