"""new fields

Revision ID: 8c12ce7bcc0a
Revises: 0adc14e989cf
Create Date: 2023-07-10 17:42:50.669753

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c12ce7bcc0a"
down_revision = "0adc14e989cf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("venue_city", sa.String(), nullable=True))
    op.add_column("event", sa.Column("venue_country", sa.String(), nullable=True))
    op.drop_column("event", "score")
    op.add_column("sales", sa.Column("currency", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sales", "currency")
    op.add_column(
        "event",
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("event", "venue_country")
    op.drop_column("event", "venue_city")
    # ### end Alembic commands ###
