"""last_update

Revision ID: 973b7f9ea7cf
Revises: 82c72be5643a
Create Date: 2024-01-09 13:24:15.668374

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "973b7f9ea7cf"
down_revision = "82c72be5643a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event", sa.Column("last_update", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event", "last_update")
    # ### end Alembic commands ###
