"""remove unique user_id field in message

Revision ID: 982e1aa38c99
Revises: cb4fb4355c24
Create Date: 2023-12-13 18:10:49.443573

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "982e1aa38c99"
down_revision = "cb4fb4355c24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_message_user_id", table_name="message")
    op.create_index(op.f("ix_message_user_id"), "message", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_user_id"), table_name="message")
    op.create_index("ix_message_user_id", "message", ["user_id"], unique=False)
    # ### end Alembic commands ###
