"""add admin model

Revision ID: f9ea2453a9bf
Revises: 21ae947371ad
Create Date: 2023-09-19 00:03:43.762056

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f9ea2453a9bf"
down_revision = "21ae947371ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column(
            "notification_level",
            sa.Enum(
                "INFO", "WARNING", "ERROR", "CRITICAL", name="adminnotificationlevel"
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin")
    # ### end Alembic commands ###
